- addon/components/simple-chart-stacked-bar.js
- app/components/simple-chart-stacked-bar.js
- tests/dummy/app/controllers/application.js
- tests/dummy/app/templates/application.hbs
- tests/integration/components/simple-chart-stacked-bar-test.js
Need to reformat the data and JS for this chart
> Add stacked bar chart

- addon/components/simple-chart-stacked-bar.js
- tests/dummy/app/styles/_variables.scss
- tests/dummy/app/styles/components/simple-charts.scss
- tests/dummy/app/templates/application.hbs
3 columns for desktop view. 1 column for mobile view. Added a little styling.  
Jon, I will clean up SCSS if you would like to go with the CSS Grid option.
> Add CSS Grid. Fix Data set for stacked bar chart.

- README.md
- package.json
Just some general cleanup to remove the boilerplate and have something
that looks real.
> Improve README and description

- addon/components/simple-chart-bar.js
- addon/components/simple-chart-donut.js
- addon/components/simple-chart-horz-bar.js
- addon/components/simple-chart-pie.js
- addon/components/simple-chart-tooltip.js
- addon/components/simple-chart.js
- addon/styles/addon.scss
- addon/styles/components/simple-chart-line.scss
- addon/styles/components/simple-chart.scss
- addon/styles/components/simple-charts-tooltip.scss
- addon/templates/components/simple-chart-tooltip.hbs
- addon/templates/components/simple-chart.hbs
- package.json
- tests/dummy/app/initializers/chart-data.js
- tests/dummy/app/templates/chart-bar.hbs
- tests/dummy/app/templates/chart-donut.hbs
- tests/dummy/app/templates/chart-horz-bar.hbs
- tests/dummy/app/templates/chart-pie.hbs
- yarn.lock
This gives us access to some tether options that make it much easier to
position the tooltip well. In order to deal with variable space and
screen sizes I pinned the dialog so that it will remain mostly in place,
but relatively close to the item the mouse it over.
Fixes #16
> Use a modal dialog for tooltips

- .gitignore
- .travis.yml
- config/ember-try.js
- ember-cli-build.js
- package.json
- testem.js
- tests/dummy/app/app.js
- tests/dummy/app/styles/app.scss
- tests/dummy/config/environment.js
- tests/dummy/config/targets.js
- tests/helpers/module-for-acceptance.js
- yarn.lock
Ran `ember init` and updated dependencies
Ran `yarn upgrade` to grab sub-level dependency updates
> Update ember-cli to v2.14.2

- package.json
Ensure that NPM and EmberObserver can see inside.
> Add our repository to package.json

- .travis.yml
Keeps yarn.lock up to date when greenkeeper makes changes.
> Enable greenkeeper lockfile update

- addon/components/simple-chart-donut.js
- addon/components/simple-chart-pie.js
- addon/mixins/chart-properties.js
- addon/styles/components/simple-chart.scss
- addon/templates/components/simple-chart-tooltip.hbs
- index.js
- package.json
- yarn.lock
Bunch of stuff that came up while I was integrating with ilios/frontend.
> Improvements (various)

- addon/components/simple-chart-donut.js
- addon/styles/components/simple-chart.scss
- addon/styles/components/simple-charts-tooltip.scss
- addon/templates/components/simple-chart-tooltip.hbs
No need to style the tooltip too much.  Also removed the overlay to help with hover flicker issues.
> Improve tooltip

- addon/mixins/chart-properties.js
After the component is destroyed it might still get some events so we
need to handle those gracefully.
> Handle resize events when the component is off the screen

- .travis.yml
- addon/components/simple-chart-bar.js
- addon/components/simple-chart-donut.js
- addon/components/simple-chart-horz-bar.js
- addon/components/simple-chart-pie.js
Everything else was in place to handle clicks - just missing the actual
handlers.
> Add click handlers to charts

- .travis.yml
- package.json
- yarn.lock
> fix(package): update ember-d3 to version 0.4.1

- addon/components/simple-chart-donut.js
- addon/components/simple-chart-pie.js
Need to destructure the data here in order to pass the correct info
back up.
> Fix data when clicking donut and pie

- addon/components/simple-chart-bar.js
- addon/components/simple-chart-donut.js
- addon/components/simple-chart-horz-bar.js
- addon/components/simple-chart-pie.js
- addon/components/simple-chart.js
- addon/templates/components/simple-chart.hbs
- package.json
- yarn.lock
By using a task we can ensure that we don't hover/leave/hover/leave
rapidly when moving between the label and the chart element. This allows
a simplification of what needs to be handled by each chart.
> Improve mouse actions (click, hover, leave)

- package.json
- yarn.lock
> fix(package): update ember-tether to version 1.0.0-beta.2

- package.json
> chore(package): update ember-source to version 3.1.1

- addon/components/simple-chart-bar.js
- addon/components/simple-chart-donut.js
- addon/components/simple-chart-horz-bar.js
- addon/components/simple-chart-pie.js
- package.json
- tests/dummy/app/lib/chart-data.js
- yarn.lock
Also our old color system doesn't work anymore so we had to do something
different.
Closes: #47 
Closes: #59
> Update D3 5.4.0

- yarn.lock
Updates everything to the latest semver possibilities.
> Remove and re-create yarn.lock file

- addon/components/simple-chart-cluster.js
- app/components/simple-chart-cluster.js
- tests/acceptance/rendered-charts-test.js
- tests/dummy/app/lib/chart-data.js
- tests/dummy/app/router.js
- tests/dummy/app/routes/chart-cluster.js
- tests/dummy/app/templates/chart-cluster.hbs
- tests/dummy/app/templates/index.hbs
- tests/integration/components/simple-chart-cluster-test.js
Allows visualizing a tree of data
> Add cluster chart

- addon/components/simple-chart-bar.js
- addon/components/simple-chart-cluster.js
- addon/components/simple-chart-donut.js
- addon/components/simple-chart-horz-bar.js
- addon/components/simple-chart-pie.js
This is way more legible at the outer edges.
> Replace orange with sinebow color scheme

- addon/components/simple-chart-pack.js
- app/components/simple-chart-pack.js
- tests/acceptance/rendered-charts-test.js
- tests/dummy/app/lib/chart-data.js
- tests/dummy/app/router.js
- tests/dummy/app/routes/chart-pack.js
- tests/dummy/app/templates/chart-pack.hbs
- tests/dummy/app/templates/index.hbs
- tests/integration/components/simple-chart-pack-test.js
Allows visualizing the relative value of a hierarchical group.
> Add Pack chart

- addon/components/simple-chart-cluster.js
- addon/components/simple-chart-pack.js
When null is sent for the data we need to supply something to
hierarchy. When the chart is very large we need to set a max size for
the nodes in a cluster.
> Fix some issues with cluster and pack charts

- package.json
- yarn.lock
This causes less conflicts with downstream consumers and is a better way
to provide our addon.
> Float our dependencies

- .travis.yml
- README.md
- package.json
In preparation for a move to dependabot
> Remove greenkeeper

- config/ember-try.js
This will clear the warning when we test and works better
> Add useYarn flag to ember-try

- package.json
- yarn.lock
While we're waiting for a release tag this will fix issues with tether
not being imported into apps.
> Pin ember tether to commit

- .eslintrc.js
- addon/components/simple-chart-bar.js
- addon/components/simple-chart-donut.js
- addon/components/simple-chart-horz-bar.js
- addon/components/simple-chart-pie.js
- tests/dummy/app/lib/chart-data.js
- tests/dummy/config/environment.js
kinda surprised this wasn't in the defaults but there ya go....
> add linting for semicolons; add a handful of missing semicolons

- addon/components/simple-chart-tooltip.js
- addon/templates/components/simple-chart-tooltip.hbs
- addon/templates/components/simple-chart.hbs
- package.json
- tests/integration/components/simple-chart-tooltip-test.js
- yarn.lock
Tether is maybe abandoned and hopefully popper solves our issues with
dependencies of ember-tether.
> Switch from tether to popper

- .template-lintrc.js
- .travis.yml
- addon/components/simple-chart-tooltip.js
- addon/components/simple-chart.js
- addon/templates/components/simple-chart-tooltip.hbs
- addon/templates/components/simple-chart.hbs
- package-lock.json
- package.json
- tests/dummy/app/templates/docs.hbs
- tests/dummy/app/templates/docs/bar.hbs
- tests/dummy/app/templates/docs/cluster.hbs
- tests/dummy/app/templates/docs/donut.hbs
- tests/dummy/app/templates/docs/horz-bar.hbs
- tests/dummy/app/templates/docs/index.hbs
- tests/dummy/app/templates/docs/pack.hbs
- tests/dummy/app/templates/docs/pie.hbs
- tests/dummy/app/templates/docs/tree.hbs
- tests/dummy/app/templates/index.hbs
- tests/dummy/app/templates/not-found.hbs
Conform to the rules of this linter by being specific about where
arguments are coming from in components.
> Use the Ilios hbs linter

- addon/components/simple-chart.hbs
- addon/components/simple-chart.js
This is provided by ember truth helpers, but we don't need it for this
one thing.
> Remove usage of or helper

- .dependabot/config.yaml
I've added a config for our sub-app /docs and turned on auto-merging for
everything since we have good tests as well as visual regression testing
there isn't anything we'd need to review.
> Improved Dependabot Config

- tests/dummy/app/controllers/application.js
- tests/dummy/app/templates/application.hbs
This makes it easier to see in the test app what is working by adding
hover and click.
> Add more testable stuff

- .github/dependabot.yml
- .github/workflows/auto-merge.yml
We don't need updates as frequently for this repo and we can auto merge
anything that isn't ignored as our test coverage and visual test
coverage are both excellent.
> Improve dependabot

- addon/components/simple-chart-bar.js
- addon/components/simple-chart-horz-bar.js
- tests/dummy/app/controllers/application.js
- tests/dummy/app/lib/chart-data.js
- tests/integration/components/simple-chart-bar-test.js
- tests/integration/components/simple-chart-donut-test.js
- tests/integration/components/simple-chart-horz-bar-test.js
- tests/integration/components/simple-chart-pie-test.js
fixes https://github.com/ilios/ember-simple-charts/issues/790
> corrects input to click- and hover-event handlers for bar/horz-bar charts

- package-lock.json
- package.json
Going back to a more stable version, will wait for ember-cli and
community to further validate this new version.
> Back out of ember-auto-import version

- docs/package-lock.json
- docs/package.json
- package-lock.json
- package.json
Which requires installing and providing webpack ourselves.
> Update to ember auto import v2

- packages/docs/app/lib/chart-data.js
- packages/docs/app/router.js
- packages/docs/app/routes/box.js
- packages/docs/app/templates/box.hbs
- packages/docs/app/templates/index.hbs
- packages/docs/tests/acceptance/rendered-charts-test.js
- packages/ember-simple-charts/addon/components/simple-chart-bar.js
- packages/ember-simple-charts/addon/components/simple-chart-box.hbs
- packages/ember-simple-charts/addon/components/simple-chart-box.js
- packages/ember-simple-charts/addon/components/simple-chart-cluster.js
- packages/ember-simple-charts/addon/components/simple-chart-horz-bar.js
- packages/ember-simple-charts/addon/components/simple-chart-pack.js
- packages/ember-simple-charts/addon/components/simple-chart-pie.js
- packages/ember-simple-charts/addon/components/simple-chart-tree.js
- packages/ember-simple-charts/addon/components/simple-chart.js
- packages/ember-simple-charts/app/components/simple-chart-box.js
- packages/test-app/app/lib/chart-data.js
- packages/test-app/app/templates/application.hbs
- packages/test-app/tests/acceptance/rendered-charts-test.js
- packages/test-app/tests/integration/components/simple-chart-box-test.js
This chart takes data like the other charts and then provides a box matching the color of a specific data point for use in a legend.
> Add a Box Chart

- package-lock.json
- packages/test-app/app/helpers/noop.js
- packages/test-app/package.json
- packages/test-app/tests/integration/helpers/noop-test.js
fixes https://github.com/ilios/ilios/issues/4493
> replaces dependency on ember-composable-helpers

- packages/ember-simple-charts/addon/styles/components/simple-charts-tooltip.scss
fixes https://github.com/ilios/ilios/issues/4616
> adds z-index to tooltip to prevent content from bleeding through.

- packages/docs/app/lib/chart-data.js
- packages/ember-simple-charts/README.md
- packages/ember-simple-charts/addon/components/simple-chart-bar.js
- packages/ember-simple-charts/addon/components/simple-chart-cluster.js
- packages/ember-simple-charts/addon/components/simple-chart-donut.js
- packages/ember-simple-charts/addon/components/simple-chart-horz-bar.js
- packages/ember-simple-charts/addon/components/simple-chart-pack.js
- packages/ember-simple-charts/addon/components/simple-chart-pie.js
- packages/ember-simple-charts/addon/components/simple-chart-tree.js
- packages/test-app/app/lib/chart-data.js
- packages/test-app/tests/integration/components/simple-chart-bar-test.js
- packages/test-app/tests/integration/components/simple-chart-cluster-test.js
- packages/test-app/tests/integration/components/simple-chart-donut-test.js
- packages/test-app/tests/integration/components/simple-chart-horz-bar-test.js
- packages/test-app/tests/integration/components/simple-chart-pack-test.js
- packages/test-app/tests/integration/components/simple-chart-pie-test.js
- packages/test-app/tests/integration/components/simple-chart-tree-test.js
> Adds description elements to charts.

- package-lock.json
- package.json
This reverts commit fe29990f66d01556c032bcda4ebc696abe0bec9b.
> Revert "1.1.0"

- .github/dependabot.yml
> rm duplicate entries in dependabot config.

- package-lock.json
- package.json
- packages/docs/package.json
- packages/ember-simple-charts/package.json
- packages/test-app/package.json
refs https://github.com/ilios/common/pull/3319
> update ember-concurrency to v3.

- .github/workflows/tag_version.yaml
pnpm version doesn't actually exist or work, we need to do a little bit more to get a good tag from this workflow.
> Fix release tagging

- .github/workflows/update-transitive-dependencies.yaml
re-creates https://github.com/ilios/ember-simple-charts/pull/1099
> bump peter-evans/create-pull-request GH action to v6.

- .github/workflows/auto-merge.yml
copy/pasted from ilios/frontend, then pruned non-applicable dependencies from the list.
> updates auto-merge workflow config.

- .github/workflows/ci.yaml
- .github/workflows/create_release.yaml
- .github/workflows/release.yaml
- .github/workflows/update-transitive-dependencies.yaml
> bump setup-node gh action to v4.

- .husky/pre-commit
- package.json
- pnpm-lock.yaml
> adds Husky integration

- docs/app/styles/app.scss
> Improve sample code line breaks

- .github/workflows/push-dist.yml
- .github/workflows/release.yaml
- .github/workflows/update-transitive-dependencies.yaml
We specify this in package.json now
> Remove Specific PNPM Version

- .github/workflows/update-pnpm-version.yml
Instead of installing pnpm in this action we can use npm. Also for the lols.
> Use npm to get pnpm Version

- .github/workflows/update-pnpm-version.yml
I was asking for this to execute the pnpm version string, not store it.
> Fix Bash Tics

- docs/app/components/click-example.hbs
- docs/app/components/example.hbs
- docs/app/components/icon-example.hbs
- docs/app/components/responsive-example.hbs
- docs/app/components/sample-code.hbs
- docs/app/components/tooltip-example.hbs
- docs/app/templates/index.hbs
- docs/package.json
- docs/tests/test-helper.js
- pnpm-lock.yaml
- test-app/package.json
- test-app/tests/index.html
- test-app/tests/integration/helpers/noop-test.js
- test-app/tests/test-helper.js
This sets up both `/docs` and `/test-app`, but doesn't yet touch CI.
> Configure app to test for a11y and fix violations

- .github/workflows/create_release.yaml
> fix up release creation workflow.
