tests/dummy/app/styles/_variables.scss
tests/dummy/app/styles/app.scss
tests/dummy/app/styles/components/simple-charts-tooltip.scss

Added CSS for tooltip styling. We will need to add this to the ilios/frontend repo.

Tooltip styles for ember-simple-charts

---

addon/components/simple-chart.js

When we're working with transient mouse events promises are rejected
when a task is canceled and I think we can safely ignore these issues.

Ignore rejected promises

---

addon/mixins/chart-properties.js
package.json
yarn.lock

Turns out that only chrome supports the Resize Observer we were using,
thankfully there is an addon that can help with this. The other issue is
that clientHeight and clientWidth were not correct on firefox, however
the getBoundingClientRect() method returns a container we can use.

Fix rendering

---

package.json

This needs to be available in the containing application.

Move ember-resize-aware into dependencies

---

addon/components/simple-chart-bar.js
addon/components/simple-chart-donut.js
addon/components/simple-chart-horz-bar.js
addon/components/simple-chart-pie.js
addon/components/simple-chart.js
addon/mixins/chart-properties.js
addon/templates/components/simple-chart.hbs

Change the mouse to a cursor when someone hovers over a clickable chart
element and ensure clicking on a label is the same as clicking on the
cart element.

Improve chart clickability

---

package.json
yarn.lock

The latest ember-d3 has trouble being used as an addon dependency. Until
that is resolved let's stick with the previous version.

Lock our ember-d3 version

---

package.json
yarn.lock

This has caused us issues with the dependency linter in the past.

Don't let ember-concurrency float

---

package.json
yarn.lock

Higher versions don't work from within an addon so I'm going to pin us
to this version for now.

Lock ember-d3 version

---

.travis.yml
package.json
yarn.lock

Some of our upstream dependencies have dropped this version and it's EOL
in a few months so I think we're OK to drop it as well.

Drop support for node 6

---

.stylelintrc
.travis.yml
package.json
yarn.lock

Follows the pattern of our other apps and moves linting into a
pre-commit hook and into the travis run and takes it out of individual
tests.

Remove linting from tests

---

addon/components/simple-chart-donut.js
addon/components/simple-chart-pie.js
tests/acceptance/rendered-charts-test.js
tests/integration/components/simple-chart-donut-test.js
tests/integration/components/simple-chart-pie-test.js

Waiting for a fixed length of time wasn't working, sometimes the percy
test captured a partially loaded state, this should be a bit more
reliable.

Improve visual tests

---

addon/components/simple-chart-bar.js
addon/components/simple-chart-donut.js
addon/components/simple-chart-horz-bar.js
addon/components/simple-chart-pie.js
tests/integration/components/simple-chart-bar-test.js
tests/integration/components/simple-chart-horz-bar-test.js

Chooses either a white or black color for chart labels automatically
based on the color of the chart element they overlay.

Calculate text color based on chart color

---

addon/components/simple-chart-bar.hbs
addon/components/simple-chart-bar.js
addon/components/simple-chart-cluster.hbs
addon/components/simple-chart-cluster.js
addon/components/simple-chart-donut.hbs
addon/components/simple-chart-donut.js
addon/components/simple-chart-horz-bar.hbs
addon/components/simple-chart-horz-bar.js
addon/components/simple-chart-pack.hbs
addon/components/simple-chart-pack.js
addon/components/simple-chart-pie.hbs
addon/components/simple-chart-pie.js
addon/components/simple-chart-tree.hbs
addon/components/simple-chart-tree.js

If we don't pass this to the `{{did-update}}` render modifier then the
charts won't draw again when data is updated.

Bind the data attribute on did-update

---

.travis.yml
tests/acceptance/rendered-charts-test.js

Couple of tweaks for our Percy integration to ensure that we don't snapshot too many times and that our snapshots are more stable when loading animations are variable.

Percy Improvements

---

.travis.yml

Setting this to false just ends up being a string so requests still get
sent to the API. Setting it to an empty string disables the integration
so we don't hit up percy with a bad token.

Disable percy without sending requests

---

tests/acceptance/rendered-charts-test.js

Missing wait here that ensures all the animations have finished before
taking a snapshot.

Fix percy test for donut chart

---

.github/workflows/ci.yaml

This is a write only token so barring malicious annoyance all someone
can do with it is use up our build minutes for the month. Putting it
directly in the workflow allows snapshots to work on pull requests from
forks as well as branches.

Add Percy Token

---

.github/workflows/ci.yaml
.github/workflows/future-ci.yaml

We dropped support a while ago, but didn't update tests.

Drop node 8 in tests

---

package-lock.json
package.json

We need this to run our docs, it used to be supplied by ember-addon-docs
directly, but the latest version of fetch doesn't allow itself to be
supplied in an addon to the app, it has to be installed at the app
level.
Supersedes and closes #451

Add ember-fetch

---

package-lock.json
package.json

supersedes https://github.com/ilios/ember-simple-charts/pull/539

re-declare eslint as dev-dependency and bump version to 7.19

---

addon/styles/components/simple-chart.scss
package-lock.json
package.json

Correcting two issues here:
1) We need ember-cli-sass to be a dependency so it will bundle our css
into vendor.css to be consumed by apps.
2) There was a css reset in addon-docs that was setting our SVGs to
blocks. When that was moved into a sub-app we lost that style and needed
to apply it ourselves.

Fix svg styles

---

addon/components/simple-chart.hbs

It isn't necessary that we calculate this every millisecond, adding a
little delay is a better user experience and more performant.

Debounce resizing

---

docs/package-lock.json
docs/package.json
package-lock.json
package.json

This requires the addition of webpak to our dev dependencies so it can
be used when building tests.

[breaking] Update Ember Auto Import to v2

---

.github/workflows/update-transitive-dependenies.yaml

The defaults syntax is only for entire jobs, but we don't need that
here. Only this step is in the docs directory.

Set the working directory for this step only

---

addon/components/simple-chart-donut.js
addon/components/simple-chart-pie.js
addon/components/simple-chart.js
package-lock.json
package.json
tests/dummy/config/deprecation-workflow.js

switch to the new destroyable methods while at it. 
deprecations are emitted out of the resize modifiers plugin, which will need to be update to latest ember-modifier plugin in order for the warnings to disappear. until that happens, we'll suppress those deprecation warnings.

suppress destroyables API deprecation warnings

---

.github/workflows/tag_version.yaml

The only thing we want to tag here is the addon, unfortunately npm doesn't make that super easy so we have to increment the workspace version and then extract that new version and use it to create a tag.

Fix Tagging Workflow

---

packages/ember-simple-charts/package.json

This prevented working with ember 5.x, which we very much support.

Widen supported ember range

---

.github/dependabot.yml

We don't really want to update these, better to stick with the blueprint versions.

Ignore blueprint dependencies with dependabot

---

.github/workflows/release.yaml

All the commits are tested and this slows down our publish unnecessarily.

Remove test step from publish

---

.github/workflows/release.yaml

We publish off of a tag and pnpm doesn't love that. We have to skip this check to get publishing to work

Skip git checks when publishing

---

pnpm-lock.yaml

was seeing
```bash
$ pnpm install
Scope: all 4 workspace projects
Lockfile is up to date, resolution step is skipped
 WARN  Broken lockfile: no entry for '@babel/core@7.24.7' in pnpm-lock.yaml
 ERR_PNPM_LOCKFILE_MISSING_DEPENDENCY  The lockfile is broken! Resolution step will be performed to fix it.
packages/ember-simple-charts             |  WARN  Could not find preferred package @babel/core@7.24.7 in lockfile
packages/ember-simple-charts             |  WARN  Could not find preferred package @babel/core@7.24.7 in lockfile
packages/ember-simple-charts             |  WARN  Could not find preferred package ember-cli-babel@8.2.0(@babel/core@7.24.7) in lockfile
packages/ember-simple-charts             |  WARN  Could not find preferred package ember-cli-babel@8.2.0(@babel/core@7.24.7) in …
```

rebuilds lock file.

---

.github/workflows/ci.yaml

Percy was only taking the test-app tests because they ran last. We want them all.

Run Docs and Test App Percy Tests

---

ember-simple-charts/package.json

Netlify changed this a while ago, we didn't.

Fix homepage link

---

test-app/tests/integration/components/simple-chart-cluster-test.js
test-app/tests/integration/components/simple-chart-donut-test.js
test-app/tests/integration/components/simple-chart-pack-test.js
test-app/tests/integration/components/simple-chart-pie-test.js

Covered a lot more of the internals for these rendered charts in the integration tests. It's a bit verbose, but should be easier to spot issues in the future.
Discovered that the 100% in these tests was causing the chart to mostly render off screen which made the percy shots mostly useless.

Enhance Integration Tests

---

ember-simple-charts/src/components/simple-chart-donut.js
ember-simple-charts/src/components/simple-chart-pie.js

It turns out that the `end` event we were tracking here from D3 doesn't apply to the entire transition. Each section of the donut or pie is animated individually and end gets called for each one.
I've added a counter which gets incremented as each section animation starts and decremented when they finish. When there are none left we can go ahead and mark loading as complete and update the class to loaded.

Improve Transition Completion

---

ember-simple-charts/package.json
ember-simple-charts/src/components/simple-chart-donut.hbs
ember-simple-charts/src/components/simple-chart-donut.js
ember-simple-charts/src/components/simple-chart-pie.hbs
ember-simple-charts/src/components/simple-chart-pie.js
pnpm-lock.yaml

Still not getting a reliable response from our loading indicator and causing percy to shoot too soon. Instead we can store the promise when we create a transition that will resolve when it is complete. If that promise isn't set yet, or isn't resolved we're in a 'loading' state.
Had the added benefit of hiding the defensive programming around a destroyed component. When the component is destroyed this getter won't fire anyway.

Replace Loading Logic

---

ember-simple-charts/src/components/simple-chart-donut.js
ember-simple-charts/src/components/simple-chart-pie.js

donut and pie charts now do not animate if they are displayed as icons

---

ember-simple-charts/src/components/simple-chart-cluster.js
ember-simple-charts/src/components/simple-chart-donut.js
ember-simple-charts/src/components/simple-chart-pack.js
ember-simple-charts/src/components/simple-chart-pie.js
ember-simple-charts/src/components/simple-chart-tree.js

On initial render height and width are sometimes zero which causes D3 to calculate the internal state of these items incorrectly. We used to have this check, now we have it again.

Restore Check for Zero Size

---

ember-simple-charts/package.json
ember-simple-charts/src/components/simple-chart-bar.js
ember-simple-charts/src/components/simple-chart-donut.js
ember-simple-charts/src/components/simple-chart-horz-bar.js
ember-simple-charts/src/components/simple-chart-pie.js
ember-simple-charts/src/helpers/slice-color.js
ember-simple-charts/src/utils/slice-color.js

Helps clean up redundant code to determine the slice color in `Bar`, `Donut`, `HorzBar`, and `Pie` chart types

Add SliceColor helper

---

docs/package.json
pnpm-lock.yaml
test-app/package.json

This 4.0.5 release widens the dependency range for @ember/test-waiters which ember-async-data isn't ready for. Locking the version for now while we await a resolution.

Pin @ember/test-helpers Version

---

ember-simple-charts/src/components/simple-chart-bar.js
ember-simple-charts/src/components/simple-chart-donut.js
ember-simple-charts/src/components/simple-chart-horz-bar.js
ember-simple-charts/src/components/simple-chart-pie.js
test-app/tests/integration/components/simple-chart-bar-test.js
test-app/tests/integration/components/simple-chart-horz-bar-test.js
test-app/tests/integration/components/simple-chart-pie-test.js

Fixes #1245 
The attribute for changing the color of text is `fill`, not `color`, so I swapped it for the charts that use text.

Fixed YIQ contrast function for text color

---

ember-simple-charts/src/components/simple-chart-horz-bar.js

I tried nudging things around here and there, but I couldn't quite get a perfect "outline" effect to work for both Mozilla and Webkit rendering. This solution doesn't use any [Magic Numbers], at least.

Turn on opt-out text-outline for HorzBar type

---

.github/workflows/tag_version.yaml
package.json

this is a partial realignment with the corresponding workflow definition in ilios/frontend.
for reference, please see https://github.com/ilios/frontend/commit/0ec2e365345b245d9041f0290307b9db06e81827

bump setup-node action version, pnpm to v22, and use pnpx over npx
